### ISSUE TITLE
history size  wrong in market watcher display

### ISSUE THREAD

**Issue by H256** [H256/gekko#2]
From @ethcar: Hi,
I have been running the UI, and it works fine, however I just noticed that for any strategy I use History size is always 1 minute, I setup multiple watchers and and ran the papertrader.

Is it okay, or just a viual glich because I always fill the parameter to use history size of 1 or 2 hours atleast.
I noticed it today. To test this I am will run a new instance of old UI with same parameters and check.

If there is bug, and if you get time to fix it, let me know.

Thank you for your time and help
Screenshot:
http://prntscr.com/mnsjpp

**Comment by H256** [comment]
@ethcar this is simply an display issue imo. 
I have updated it to display the history size in minutes also. Just `git pull` and replace `web/vue` **without** overwriting `web/vue/statics/UiConfig.js`.

**Comment by ethcar** [comment]
Thanks for your response, yes it looks like to be just the visual part. Its fine.
Incase if I create a new instance I will use the updated repo. 
I should not be facing any issues, New UI is working fine on my server and I have no issues anymore.

Thank you
